default: &default
  secret_key_base: ENV["SECRET_KEY_BASE"]
  FACEBOOK_KEY: '317030188459984'
  FACEBOOK_SECRET: 'd371b904e89b5a594cbaf6585df9bc14'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
