default: &default
  secret_key_base: ENV["SECRET_KEY_BASE"]
  FACEBOOK_KEY: '317030188459984'
  FACEBOOK_SECRET: 'd371b904e89b5a594cbaf6585df9bc14'
  TWITTER_KEY: 'db82QDiL6n6Adl1L59doqeR2n'
  TWITTER_SECRET: 'ylV3TSh8IvvjMDFcnunTfZJX2AJqosenBAgn0pSlvEucDfaHVu'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
